/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekspedisi.PanelComponent;

/**
 *
 * @author GUE
 */
public class NavBar extends javax.swing.JPanel {

    /**
     * Creates new form NavBar
     */
    public NavBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bukuBtn1 = new ekspedisi.component.BukuBtn();
        homeBtn1 = new ekspedisi.component.HomeBtn();
        orderBtn1 = new ekspedisi.component.OrderBtn();
        tagihanBtn1 = new ekspedisi.component.TagihanBtn();
        pembayaranBtn1 = new ekspedisi.component.PembayaranBtn();
        premiBtn1 = new ekspedisi.component.PremiBtn();
        laporanBtn1 = new ekspedisi.component.LaporanBtn();
        direktoriBtn1 = new ekspedisi.component.DirektoriBtn();
        logoutBtn1 = new ekspedisi.component.LogoutBtn();

        setBackground(new java.awt.Color(255, 255, 255));

        bukuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuBtn1ActionPerformed(evt);
            }
        });

        homeBtn1.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(direktoriBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(laporanBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bukuBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(premiBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tagihanBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembayaranBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(homeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(orderBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(orderBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tagihanBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pembayaranBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(premiBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(bukuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(laporanBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(direktoriBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bukuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bukuBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ekspedisi.component.BukuBtn bukuBtn1;
    private ekspedisi.component.DirektoriBtn direktoriBtn1;
    private ekspedisi.component.HomeBtn homeBtn1;
    private ekspedisi.component.LaporanBtn laporanBtn1;
    private ekspedisi.component.LogoutBtn logoutBtn1;
    private ekspedisi.component.OrderBtn orderBtn1;
    private ekspedisi.component.PembayaranBtn pembayaranBtn1;
    private ekspedisi.component.PremiBtn premiBtn1;
    private ekspedisi.component.TagihanBtn tagihanBtn1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the bukuBtn1
     */
    public ekspedisi.component.BukuBtn getBukuBtn1() {
        return bukuBtn1;
    }

    /**
     * @return the direktoriBtn1
     */
    public ekspedisi.component.DirektoriBtn getDirektoriBtn1() {
        return direktoriBtn1;
    }

    /**
     * @return the homeBtn1
     */
    public ekspedisi.component.HomeBtn getHomeBtn1() {
        return homeBtn1;
    }

    /**
     * @return the laporanBtn1
     */
    public ekspedisi.component.LaporanBtn getLaporanBtn1() {
        return laporanBtn1;
    }

    /**
     * @return the logoutBtn1
     */
    public ekspedisi.component.LogoutBtn getLogoutBtn1() {
        return logoutBtn1;
    }

    /**
     * @return the orderBtn1
     */
    public ekspedisi.component.OrderBtn getOrderBtn1() {
        return orderBtn1;
    }

    /**
     * @return the pembayaranBtn1
     */
    public ekspedisi.component.PembayaranBtn getPembayaranBtn1() {
        return pembayaranBtn1;
    }

    /**
     * @return the premiBtn1
     */
    public ekspedisi.component.PremiBtn getPremiBtn1() {
        return premiBtn1;
    }

    /**
     * @return the tagihanBtn1
     */
    public ekspedisi.component.TagihanBtn getTagihanBtn1() {
        return tagihanBtn1;
    }
}
